{
 "title": "Dashboard TP1 IoT",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Alertes température > 32°C",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "query": "from(bucket: \"raw_7d\")\r\n  |> range(start: -30m)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> filter(fn: (r) => r._value > 32.0)\r\n  |> yield(name: \"alertes_temperature\")"
    }
   ]
  },
  {
   "title": "Humidité actuelle",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "from(bucket: \"raw_7d\")\r\n  |> range(start: -1h)\r\n  |> filter(fn: (r) => r._measurement == \"environment\")\r\n  |> filter(fn: (r) => r._field == \"humidity\")\r\n  |> last()\r\n  |> yield(name: \"derniere_valeur\")"
    }
   ]
  },
  {
   "title": "Température en temps réel",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "targets": [
    {
     "query": "from(bucket: \"raw_7d\")\r\n  |> range(start: -24h)\r\n  |> filter(fn: (r) => r._field == \"temperature\")\r\n  |> aggregateWindow(every: 1h, fn: mean, createEmpty: false)\r\n  |> yield(name: \"temp_moyenne_horaire\")"
    }
   ]
  }
 ]
}