[agent]
  interval = '10s'
  flush_interval = '10s'

[[inputs.mqtt_consumer]]
  servers = ['tcp://mosquitto:1883']
  topics = ['iot/CI/abidjan/#']
  data_format = 'influx'

[[outputs.influxdb_v2]]
  urls = ['http://influxdb:8086']
  token = 'CMoeH6EafIycmTdbFCHEa-ODN0XjZ5DBjr8TvsXAytY4a_bjYXAd1H4EMqSxT6x_FrFWZ-Pqm8u5Ee6rkKkfcQ=='
  organization = 'UFHB-IoT'
  bucket = 'raw_7d'
